# Generated by Django 3.2.4 on 2021-08-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='isVanity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='shortURL',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
